# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default=b'img/categories/cake.png', upload_to=b'img/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=b'Title')),
                ('image', models.ImageField(default=b'img/groups/default-img.gif', upload_to=b'img/groups/')),
                ('description', models.TextField(verbose_name=b'Description')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Created')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name=b'Category')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'Female', b'Female'), (b'Male', b'Male')], default=b'Female', max_length=200)),
                ('dob', models.DateField(null=True, verbose_name=b'Date of Birth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=b'Title')),
                ('text', models.TextField(verbose_name=b'Text')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Group', verbose_name=b'Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', to='core.Member'),
        ),
    ]
