# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text=b'sds', max_length=200, verbose_name=b'Title'),
        ),
    ]
