# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180202_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category_ref',
            field=models.ForeignKey(help_text=b'Specify the category', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text=b'Add a short description', verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default=b'img/groups/default-img.gif', upload_to=b'img/groups/', verbose_name=b'Image'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text=b'Add a title for your desired group', max_length=200, verbose_name=b'Title'),
        ),
    ]
