# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180205_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default=b'img/groups/default-img.gif', null=True, upload_to=b'img/groups/', verbose_name=b'Image'),
        ),
    ]
