# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171031_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='img/categories/cake.png', upload_to='img/categories/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='img/groups/default-img.gif', upload_to='img/groups/'),
        ),
    ]
